# Generated by Django 5.0.6 on 2024-05-30 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='ExerciseDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_the_week', models.IntegerField()),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary_app.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(null=True)),
                ('reps', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary_app.exerciseday')),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary_app.exercise')),
            ],
        ),
        migrations.DeleteModel(
            name='ExerciseList',
        ),
    ]
