# Generated by Django 5.0.6 on 2024-05-30 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0002_exercise_description_exerciseday_exercisedone_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExerciseDay',
            new_name='Day',
        ),
        migrations.RenameModel(
            old_name='ExerciseDone',
            new_name='Done',
        ),
    ]
